import numpy as np

from .mfc_utils import compute_noise_cost_matrix


def make_lambda_grid(max_lambda: float = 1000.0) -> np.ndarray:
 """
 Builds a lambda grid with resolution near zero and enough reach for small
 positive robustness radii. The m=0 case is handled exactly and does not use
 this grid.
 """
 linear = np.linspace(0.0, 100.0, 26)
 log = np.geomspace(1.0, max_lambda, 20)
 return np.unique(np.concatenate(([0.0], linear, log)))


def _get_noise_cost_matrix(tables: dict, q_norm: int) -> np.ndarray:
 """
 Returns |e - e_tilde|^q on the common-noise grid, as in the paper.
 """
 if "noise_grid" not in tables:
  raise KeyError("precomputed tables must include the common-noise grid")

 cache = tables.setdefault("noise_cost_power", {})
 if q_norm not in cache:
  cache[q_norm] = compute_noise_cost_matrix(tables["noise_grid"], q_norm)
 return cache[q_norm]


def compute_robust_bellman_target(
 Q: np.ndarray,
 tables: dict,
 robust_m: float,
 q_norm: int,
 p_hat: np.ndarray,
 lambda_grid: np.ndarray,
 discount: float,
 s_idx: int = None,
 a_idx: int = None,
) -> np.ndarray:
 """
 Computes the common-noise robust Bellman target.

 If s_idx and a_idx are given, computes the scalar target for that
 state-action pair. Otherwise, computes targets for all state-action pairs.
 """
 S = tables["S"]
 A = tables["A"]
 transition_table = tables["transition_table"]
 reward_table = tables["reward_table"]
 p_hat = np.asarray(p_hat, dtype=float)
 p_hat = p_hat / np.sum(p_hat)

 penalty = robust_m ** q_norm
 V_next = np.max(Q, axis=1)

 if s_idx is not None and a_idx is not None:
  next_indices = transition_table[s_idx, a_idx, :]
  J_next = V_next[next_indices]

  if robust_m <= 0.0:
   return reward_table[s_idx, a_idx] + discount * float(np.dot(p_hat, J_next))

  noise_cost = _get_noise_cost_matrix(tables, q_norm)
  lambdas = np.asarray(lambda_grid, dtype=float)
  candidates = J_next[None, None, :] + lambdas[:, None, None] * noise_cost[None, :, :]
  inner_min = np.min(candidates, axis=-1)
  obj = inner_min @ p_hat - penalty * lambdas
  best_phi = float(np.max(obj))

  return reward_table[s_idx, a_idx] + discount * best_phi

 J_next = V_next[transition_table]

 if robust_m <= 0.0:
  return reward_table + discount * np.sum(p_hat * J_next, axis=-1)

 noise_cost = _get_noise_cost_matrix(tables, q_norm)
 best_phi = np.full((S, A), -np.inf)
 for lam in lambda_grid:
  candidates = J_next[:, :, None, :] + lam * noise_cost[None, None, :, :]
  inner_min = np.min(candidates, axis=-1)
  obj = np.sum(p_hat * inner_min, axis=-1) - penalty * lam
  best_phi = np.maximum(best_phi, obj)

 return reward_table + discount * best_phi


def compute_single_robust_target(
 Q: np.ndarray,
 s_idx: int,
 a_idx: int,
 tables: dict,
 robust_m: float,
 q_norm: int,
 p_hat: np.ndarray,
 lambda_grid: np.ndarray,
 discount: float,
 e_realized_idx: int,
 V_next: np.ndarray = None,
) -> float:
 """
 Computes the sample-based robust target using one common-noise draw.
 """
 transition_table = tables["transition_table"]
 reward_table = tables["reward_table"]
 p_hat = np.asarray(p_hat, dtype=float)
 p_hat = p_hat / np.sum(p_hat)

 penalty = robust_m ** q_norm
 if V_next is None:
  V_next = np.max(Q, axis=1)

 next_indices = transition_table[s_idx, a_idx, :]
 J_next = V_next[next_indices]
 mu_next_idx = next_indices[e_realized_idx]

 if robust_m <= 0.0:
  return reward_table[s_idx, a_idx] + discount * V_next[mu_next_idx]

 noise_cost = _get_noise_cost_matrix(tables, q_norm)
 lambdas = np.asarray(lambda_grid, dtype=float)
 candidates = J_next[None, None, :] + lambdas[:, None, None] * noise_cost[None, :, :]
 inner_min = np.min(candidates, axis=-1)
 obj = inner_min @ p_hat - penalty * lambdas
 best_lam = float(lambdas[int(np.argmax(obj))])

 lc_eval = float(np.min(J_next + best_lam * noise_cost[e_realized_idx, :]))
 robust_continuation = lc_eval - penalty * best_lam
 return reward_table[s_idx, a_idx] + discount * robust_continuation


def run_async_qlearning(
 tables: dict,
 robust_m: float,
 discount: float,
 q_norm: int,
 p_hat: np.ndarray,
 lambda_grid: np.ndarray,
 num_updates: int = None,
 num_episodes: int = None,
 T_episode: int = 10,
 w_lr: float = 0.7,
 coverage_passes: int = 0,
 interleaved_coverage_passes: int = 0,
 interleaved_coverage_interval: int = 0,
):
 """
 Runs asynchronous Q-learning using a pre-sampled state-action sequence.

 The sequence is generated by repeated random permutations of all
 state-action pairs, independent of Q and of common-noise samples.
 """
 S, A = tables["S"], tables["A"]
 p_hat = np.asarray(p_hat, dtype=float)
 p_hat = p_hat / np.sum(p_hat)
 N_E = len(p_hat)
 Q = np.zeros((S, A))
 V = np.max(Q, axis=1)
 N_visits = np.zeros((S, A))

 if num_updates is None:
  if num_episodes is None:
   num_updates = 1000 * T_episode
  else:
   num_updates = int(num_episodes) * int(T_episode)
   print(
    f" Compatibility: num_updates = num_episodes * T_episode = {num_updates}"
   )
 num_updates = int(num_updates)
 if num_updates < 0:
  raise ValueError("num_updates must be nonnegative")

 record_freq = max(1, num_updates // 50) if num_updates > 0 else 1

 def update_pair(s_idx: int, a_idx: int):
  e_realized_idx = np.random.choice(N_E, p=p_hat)
  target = compute_single_robust_target(
   Q, s_idx, a_idx, tables, robust_m, q_norm,
   p_hat, lambda_grid, discount, e_realized_idx, V,
  )

  lr = (N_visits[s_idx, a_idx] + 1.0) ** (-w_lr)
  Q[s_idx, a_idx] += lr * (target - Q[s_idx, a_idx])
  V[s_idx] = np.max(Q[s_idx])
  N_visits[s_idx, a_idx] += 1.0

 def run_coverage_block(num_passes: int, label: str):
  total_pairs = S * A
  flat_pairs = np.arange(total_pairs)
  print(f" {label}: {num_passes} pass(es), {total_pairs} state-action pairs/pass")
  for cov_pass in range(num_passes):
   np.random.shuffle(flat_pairs)
   for flat_idx in flat_pairs:
    s_idx = flat_idx // A
    a_idx = flat_idx % A
    update_pair(s_idx, a_idx)
   coverage = np.mean(N_visits > 0) * 100
   print(f" [{label} {cov_pass+1}/{num_passes}] coverage={coverage:.1f}%")

 if coverage_passes > 0:
  run_coverage_block(coverage_passes, "Coverage warm-start")

 total_pairs = S * A
 flat_pairs = np.arange(total_pairs)
 updates_done = 0
 pass_count = 0
 while updates_done < num_updates:
  np.random.shuffle(flat_pairs)
  pass_count += 1
  for flat_idx in flat_pairs:
   s_idx = flat_idx // A
   a_idx = flat_idx % A
   update_pair(s_idx, a_idx)
   updates_done += 1

   if updates_done % record_freq == 0 or updates_done == num_updates:
    coverage = np.mean(N_visits > 0) * 100
    print(
     f" [Update {updates_done}/{num_updates}] "
     f"coverage={coverage:.1f}%, permutation_pass={pass_count}"
    )

   should_cover = (
    interleaved_coverage_passes > 0
    and interleaved_coverage_interval > 0
    and updates_done < num_updates
    and updates_done % interleaved_coverage_interval == 0
   )
   if should_cover:
    run_coverage_block(
     interleaved_coverage_passes,
     f"Interleaved coverage after update {updates_done}",
    )

   if updates_done >= num_updates:
    break

 return Q
